-- IMMUTABLE TEST FIXTURE: generated by executing the actual initializer at git 11c69f6.
-- Do not regenerate from current DDL or by subtracting current columns.
BEGIN TRANSACTION;
CREATE TABLE belief_evidence (
  belief_id TEXT NOT NULL REFERENCES current_beliefs(belief_id),
  evidence_id TEXT NOT NULL,
  relation TEXT NOT NULL,
  created_at TEXT NOT NULL,
  source_event_id TEXT NOT NULL REFERENCES brain_events(id),
  PRIMARY KEY (belief_id, evidence_id, relation)
);
CREATE TABLE brain_events (
  event_seq INTEGER PRIMARY KEY,
  id TEXT NOT NULL UNIQUE,
  ts TEXT NOT NULL,
  kind TEXT NOT NULL,
  writer TEXT NOT NULL,
  session_id TEXT,
  body_json TEXT NOT NULL,
  body_hash TEXT NOT NULL,
  prev_hash TEXT,
  event_hash TEXT NOT NULL UNIQUE
);
CREATE TABLE context_source_handle_issues (
  source_id TEXT NOT NULL REFERENCES context_source_handles(id),
  retrieval_use_id TEXT NOT NULL REFERENCES retrieval_uses(id),
  issued_at TEXT NOT NULL,
  PRIMARY KEY (source_id, retrieval_use_id)
);
CREATE TABLE context_source_handles (
  id TEXT PRIMARY KEY,
  issued_at TEXT NOT NULL,
  retrieval_use_id TEXT REFERENCES retrieval_uses(id),
  object_id TEXT NOT NULL,
  source_kind TEXT NOT NULL,
  uri TEXT,
  content_hash TEXT NOT NULL,
  scope_json TEXT NOT NULL,
  locator_json TEXT NOT NULL
);
CREATE TABLE current_beliefs (
  belief_id TEXT PRIMARY KEY,
  body TEXT NOT NULL,
  belief_type TEXT,
  attributes_json TEXT NOT NULL DEFAULT '{}',
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  visibility TEXT NOT NULL,
  egress_policy TEXT NOT NULL,
  scope_provenance TEXT NOT NULL DEFAULT 'explicit',
  confidence REAL,
  confidence_band TEXT,
  evidence_ids TEXT NOT NULL,
  status TEXT NOT NULL,
  serve INTEGER NOT NULL DEFAULT 0 CHECK (serve IN (0, 1)),
  pinned INTEGER NOT NULL DEFAULT 0 CHECK (pinned IN (0, 1)),
  approved_event_id TEXT REFERENCES brain_events(id),
  last_event_id TEXT NOT NULL REFERENCES brain_events(id),
  last_compiled_at TEXT NOT NULL
);
CREATE TABLE egress_audits (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  target TEXT NOT NULL,
  context_json TEXT NOT NULL,
  query TEXT,
  included_json TEXT NOT NULL,
  rejected_json TEXT NOT NULL,
  payload_hash TEXT NOT NULL
);
CREATE TABLE evidence_objects (
  evidence_id TEXT PRIMARY KEY,
  -- Empty for a pointer row: the text lives in the file named by
  -- metadata_json's body_ref, and `body_head` holds the recorded excerpt.
  -- See ocbrain.history_window.
  body TEXT NOT NULL,
  body_head TEXT,
  kind TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  source_content_hash TEXT,
  source_type TEXT,
  source_runtime TEXT,
  source_uri TEXT,
  artifact_uri TEXT,
  artifact_hash TEXT,
  occurred_at TEXT,
  recorded_at TEXT NOT NULL,
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  visibility TEXT NOT NULL,
  egress_policy TEXT NOT NULL,
  scope_provenance TEXT NOT NULL,
  metadata_json TEXT NOT NULL,
  recorded_event_id TEXT NOT NULL REFERENCES brain_events(id)
);
CREATE TABLE object_aliases (
  alias_id TEXT PRIMARY KEY,
  canonical_id TEXT NOT NULL,
  object_kind TEXT NOT NULL,
  source TEXT NOT NULL,
  source_event_id TEXT NOT NULL REFERENCES brain_events(id)
);
CREATE TABLE projection_cursor (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  last_event_rowid INTEGER NOT NULL,
  last_event_hash TEXT,
  updated_at TEXT NOT NULL
);
CREATE TABLE retrieval_items (
  retrieval_use_id TEXT NOT NULL REFERENCES retrieval_uses(id),
  object_id TEXT NOT NULL,
  object_kind TEXT NOT NULL,
  rank INTEGER NOT NULL,
  score REAL,
  PRIMARY KEY (retrieval_use_id, rank)
);
CREATE TABLE retrieval_uses (
  id TEXT PRIMARY KEY,
  knowledge_id TEXT,
  served_to_runtime TEXT,
  task_ref TEXT,
  affected_decision INTEGER,
  corrected INTEGER,
  outcome TEXT NOT NULL DEFAULT 'unknown',
  note TEXT,
  query_text TEXT,
  served_ids_json TEXT,
  context_json TEXT,
  packet_schema TEXT,
  session_id TEXT,
  feedback_source TEXT,
  feedback_at TEXT,
  served_at TEXT NOT NULL,
  source_event_id TEXT REFERENCES brain_events(id),
  -- Server-observed caller identity. `session_id` above stays the legacy
  -- model-supplied string; these three are what the process saw for itself.
  -- See ocbrain.provenance for what each one is worth.
  server_connection_id TEXT,
  client_session_hint TEXT,
  client_runtime_key TEXT,
  provenance_json TEXT,
  -- The folded form of `task_ref` above, so a retrieval and the closeout that
  -- links it agree on which task they belong to. NULL on historical rows.
  task_ref_norm TEXT
);
CREATE TABLE schema_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
INSERT INTO "schema_meta" VALUES('core_schema','ocbrain.core.v1');
INSERT INTO "schema_meta" VALUES('semantic_authority','brain_events');
CREATE TABLE search_documents (
  doc_id TEXT NOT NULL UNIQUE,
  kind,
  title,
  body,
  path
);
PRAGMA writable_schema=ON;
INSERT INTO sqlite_master(type,name,tbl_name,rootpage,sql)VALUES('table','search_index','search_index',0,'CREATE VIRTUAL TABLE search_index USING fts5(
  kind,
  title,
  body,
  content=''search_documents'',
  content_rowid=''rowid''
)');
CREATE TABLE 'search_index_config'(k PRIMARY KEY, v) WITHOUT ROWID;
INSERT INTO "search_index_config" VALUES('version',4);
CREATE TABLE 'search_index_data'(id INTEGER PRIMARY KEY, block BLOB);
INSERT INTO "search_index_data" VALUES(1,X'');
INSERT INTO "search_index_data" VALUES(10,X'00000000000000');
CREATE TABLE 'search_index_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE 'search_index_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE task_closeout_retrievals (
  closeout_id TEXT NOT NULL REFERENCES task_closeouts(id),
  retrieval_use_id TEXT NOT NULL REFERENCES retrieval_uses(id),
  PRIMARY KEY (closeout_id, retrieval_use_id)
);
CREATE TABLE task_closeouts (
  id TEXT PRIMARY KEY,
  schema_version TEXT NOT NULL,
  closed_at TEXT NOT NULL,
  task_ref TEXT NOT NULL,
  status TEXT NOT NULL,
  summary TEXT NOT NULL,
  decision_impact TEXT NOT NULL,
  decision_note TEXT,
  awaiting TEXT,
  runtime TEXT,
  session_id TEXT,
  context_json TEXT NOT NULL,
  artifact_refs_json TEXT NOT NULL,
  verifier_refs_json TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  receipt_json TEXT NOT NULL,
  content_hash TEXT NOT NULL UNIQUE,
  -- Server-observed caller identity, mirrored out of provenance_json so the
  -- closeout-to-transcript join is a column read. `session_id` above stays the
  -- legacy model-supplied string. See ocbrain.provenance.
  server_connection_id TEXT,
  client_session_hint TEXT,
  client_runtime_key TEXT,
  -- Chain pointers. `parent_closeout_id` is the closeout this one continues,
  -- written only when it resolved; `task_ref_norm` is the folded form of
  -- `task_ref` above, which stays verbatim. Both are NULL on every row written
  -- before they existed: the fold happens at write time and history is never
  -- rewritten. See ocbrain.closeout.normalize_task_ref.
  parent_closeout_id TEXT,
  task_ref_norm TEXT
);
CREATE INDEX idx_brain_events_kind_ts ON brain_events(kind, ts);
CREATE INDEX idx_brain_events_subject
  ON brain_events(json_extract(body_json, '$.subject.id'));
CREATE INDEX idx_brain_events_legacy_target
  ON brain_events(json_extract(body_json, '$.target_id'));
CREATE INDEX idx_brain_events_tombstone_target
  ON brain_events(json_extract(body_json, '$.target'))
  WHERE kind='tombstone_recorded';
CREATE TRIGGER brain_events_no_update
BEFORE UPDATE ON brain_events BEGIN
  SELECT RAISE(ABORT, 'brain_events is append-only');
END;
CREATE TRIGGER brain_events_no_delete
BEFORE DELETE ON brain_events BEGIN
  SELECT RAISE(ABORT, 'brain_events is append-only');
END;
CREATE INDEX idx_evidence_objects_scope
  ON evidence_objects(scope_type, scope_id);
CREATE INDEX idx_evidence_objects_source
  ON evidence_objects(source_uri, kind, recorded_at DESC);
CREATE INDEX idx_current_beliefs_scope
  ON current_beliefs(scope_type, scope_id, status, serve);
CREATE INDEX idx_belief_evidence_evidence
  ON belief_evidence(evidence_id, belief_id);
CREATE INDEX idx_object_aliases_canonical
  ON object_aliases(canonical_id);
CREATE INDEX idx_retrieval_uses_outcome_served
  ON retrieval_uses(outcome, served_at);
CREATE INDEX idx_retrieval_uses_session_hint
  ON retrieval_uses(client_session_hint, served_at);
CREATE INDEX idx_retrieval_items_object
  ON retrieval_items(object_id, retrieval_use_id);
CREATE INDEX idx_context_source_handles_retrieval
  ON context_source_handles(retrieval_use_id);
CREATE TRIGGER context_source_handle_issues_no_update
BEFORE UPDATE ON context_source_handle_issues BEGIN
  SELECT RAISE(ABORT, 'context_source_handle_issues is append-only');
END;
CREATE TRIGGER context_source_handle_issues_no_delete
BEFORE DELETE ON context_source_handle_issues BEGIN
  SELECT RAISE(ABORT, 'context_source_handle_issues is append-only');
END;
CREATE INDEX idx_task_closeouts_session_hint
  ON task_closeouts(client_session_hint, closed_at);
CREATE INDEX idx_task_closeouts_chain
  ON task_closeouts(task_ref_norm, closed_at);
CREATE INDEX idx_task_closeout_retrievals_retrieval
  ON task_closeout_retrievals(retrieval_use_id);
CREATE TRIGGER task_closeouts_no_update
BEFORE UPDATE ON task_closeouts BEGIN
  SELECT RAISE(ABORT, 'task_closeouts is append-only');
END;
CREATE TRIGGER task_closeouts_no_delete
BEFORE DELETE ON task_closeouts BEGIN
  SELECT RAISE(ABORT, 'task_closeouts is append-only');
END;
CREATE TRIGGER task_closeout_retrievals_no_update
BEFORE UPDATE ON task_closeout_retrievals BEGIN
  SELECT RAISE(ABORT, 'task_closeout_retrievals is append-only');
END;
CREATE TRIGGER task_closeout_retrievals_no_delete
BEFORE DELETE ON task_closeout_retrievals BEGIN
  SELECT RAISE(ABORT, 'task_closeout_retrievals is append-only');
END;
CREATE TRIGGER search_documents_ai AFTER INSERT ON search_documents BEGIN
  INSERT INTO search_index(rowid, kind, title, body)
  VALUES (new.rowid, new.kind, new.title, new.body);
END;
CREATE TRIGGER search_documents_ad AFTER DELETE ON search_documents BEGIN
  INSERT INTO search_index(search_index, rowid, kind, title, body)
  VALUES ('delete', old.rowid, old.kind, old.title, old.body);
END;
CREATE TRIGGER search_documents_au AFTER UPDATE ON search_documents BEGIN
  INSERT INTO search_index(search_index, rowid, kind, title, body)
  VALUES ('delete', old.rowid, old.kind, old.title, old.body);
  INSERT INTO search_index(rowid, kind, title, body)
  VALUES (new.rowid, new.kind, new.title, new.body);
END;
PRAGMA writable_schema=OFF;
COMMIT;
