-- IMMUTABLE TEST FIXTURE: generated by executing the actual initializer at git 11c69f6.
-- Do not regenerate from current DDL or by subtracting current columns.
BEGIN TRANSACTION;
CREATE TABLE autopilot_runs (
  id TEXT PRIMARY KEY,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL DEFAULT 'running',
  stages_json TEXT,
  error TEXT
);
CREATE TABLE brain_events (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  kind TEXT CHECK (
    kind IN (
      'evidence_recorded',
      'compilation_proposed',
      'compilation_decided',
      'correction_recorded',
      'tombstone_recorded',
      'scope_promoted'
    )
  ) NOT NULL,
  writer TEXT NOT NULL,
  session_id TEXT,
  body_json TEXT NOT NULL,
  body_hash TEXT NOT NULL,
  prev_hash TEXT,
  event_hash TEXT NOT NULL UNIQUE
);
CREATE TABLE context_source_handle_issues (
  source_id TEXT NOT NULL REFERENCES context_source_handles(id),
  retrieval_use_id TEXT NOT NULL REFERENCES retrieval_uses(id),
  issued_at TEXT NOT NULL,
  PRIMARY KEY (source_id, retrieval_use_id)
);
CREATE TABLE context_source_handles (
  id TEXT PRIMARY KEY,
  issued_at TEXT NOT NULL,
  retrieval_use_id TEXT REFERENCES retrieval_uses(id),
  object_id TEXT NOT NULL,
  source_kind TEXT NOT NULL,
  uri TEXT,
  content_hash TEXT NOT NULL,
  scope_json TEXT NOT NULL,
  locator_json TEXT NOT NULL
);
CREATE TABLE current_beliefs (
  belief_id TEXT PRIMARY KEY,
  body TEXT NOT NULL,
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  visibility TEXT NOT NULL,
  egress_policy TEXT NOT NULL,
  confidence REAL,
  confidence_band TEXT,
  evidence_ids TEXT NOT NULL,
  status TEXT CHECK (
    status IN ('current','superseded','retracted','tombstoned')
  ) NOT NULL DEFAULT 'current',
  pinned INTEGER NOT NULL DEFAULT 0,
  approved_event_id TEXT NOT NULL,
  last_event_id TEXT NOT NULL,
  last_compiled_at TEXT NOT NULL
);
CREATE TABLE dataset_calibrations (
  eval_id TEXT PRIMARY KEY,
  winner TEXT NOT NULL,
  reason TEXT,
  ideal_response TEXT,
  ideal_response_source TEXT,
  preference_strength TEXT,
  labeled_by TEXT,
  labeled_at TEXT NOT NULL,
  source_hash TEXT NOT NULL,
  status TEXT NOT NULL
);
CREATE TABLE dataset_examples (
  id TEXT PRIMARY KEY,
  dataset TEXT CHECK (dataset IN ('sft','dpo','persona')) NOT NULL,
  content_hash TEXT NOT NULL,
  dedup_key TEXT NOT NULL,
  source_kind TEXT CHECK (source_kind IN
    ('openclaw_session','claude_session','codex_session',
     'correction_event','git_commit','authored_doc')) NOT NULL,
  source_uri TEXT,
  source_span TEXT,
  evidence_ids TEXT NOT NULL,
  privacy_scope TEXT CHECK (privacy_scope IN ('private','workspace','project','public'))
    NOT NULL DEFAULT 'workspace',
  quality_label TEXT CHECK (quality_label IN ('good','neutral','bad','excluded')) NOT NULL,
  quality_confidence REAL,
  quality_reasons TEXT,
  n_turns INTEGER,
  n_chars INTEGER,
  example_json TEXT NOT NULL,
  session_id TEXT,
  occurred_at TEXT,
  grade_score REAL,
  grade_json TEXT,
  grade_model TEXT,
  grade_prompt_version TEXT,
  graded_at TEXT,
  train_class TEXT,
  train_class_reason TEXT,
  train_classified_at TEXT,
  train_selected INTEGER NOT NULL DEFAULT 0,
  train_selection_rank INTEGER,
  train_selection_reason TEXT,
  train_selected_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(dataset, content_hash)
);
CREATE TABLE dataset_exports (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  dataset TEXT NOT NULL,
  path TEXT NOT NULL,
  min_scope TEXT NOT NULL,
  min_label TEXT NOT NULL,
  min_grade REAL,
  format TEXT NOT NULL,
  example_count INTEGER NOT NULL,
  excluded_count INTEGER NOT NULL,
  bytes INTEGER NOT NULL,
  payload_hash TEXT NOT NULL,
  manifest_json TEXT NOT NULL,
  egress_audit_id TEXT
);
CREATE TABLE dataset_grade_runs (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  item_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  request_hash TEXT,
  error TEXT
);
CREATE TABLE dataset_sources (
  source_uri TEXT NOT NULL,
  dataset TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  mined_at TEXT NOT NULL,
  examples_emitted INTEGER NOT NULL DEFAULT 0,
  status TEXT CHECK (status IN ('mined','skipped','error')) NOT NULL DEFAULT 'mined',
  detail TEXT,
  PRIMARY KEY (source_uri, dataset)
);
CREATE TABLE egress_audits (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  target TEXT NOT NULL,
  context_json TEXT NOT NULL,
  query TEXT,
  included_json TEXT NOT NULL,
  rejected_json TEXT NOT NULL,
  payload_hash TEXT NOT NULL
);
CREATE TABLE embed_runs (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  items INTEGER NOT NULL DEFAULT 0,
  cost_usd REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  error TEXT
);
CREATE TABLE evidence (
  id TEXT PRIMARY KEY,
  source_type TEXT NOT NULL,
  source_runtime TEXT,
  source_uri TEXT,
  content_hash TEXT NOT NULL,
  claim TEXT NOT NULL,
  artifact_uri TEXT,
  artifact_hash TEXT,
  verifier_status TEXT CHECK (
    verifier_status IN ('unknown','passed','failed','not_required')
  ) DEFAULT 'unknown',
  loop_tags TEXT,
  project TEXT,
  privacy_scope TEXT CHECK (
    privacy_scope IN ('private','workspace','project','public')
  ) DEFAULT 'workspace',
  occurred_at TEXT,
  ingested_at TEXT NOT NULL, injection_scan_status TEXT, injection_scan_hits TEXT,
  UNIQUE(source_uri, content_hash)
);
CREATE TABLE family_scores (
  loop_id TEXT NOT NULL,
  family TEXT NOT NULL,
  attempts INTEGER,
  kept INTEGER,
  reverted INTEGER,
  approach_failures INTEGER,
  verifier_pass_rate REAL,
  mean_primary_delta REAL,
  recency TEXT,
  state TEXT CHECK (
    state IN ('promising','exhausted','blocked','risky','stale','untried')
  ),
  refreshed_at TEXT,
  PRIMARY KEY (loop_id, family)
);
CREATE TABLE harvest_watermarks (
  domain TEXT NOT NULL,
  stream TEXT NOT NULL,
  watermark TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (domain, stream)
);
CREATE TABLE judge_runs (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL,
  model TEXT NOT NULL,
  status TEXT NOT NULL,
  item_count INTEGER NOT NULL DEFAULT 0,
  request_hash TEXT,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  cost_usd REAL NOT NULL DEFAULT 0,
  response_json TEXT,
  egress_audit_id TEXT
);
CREATE TABLE knowledge (
  id TEXT PRIMARY KEY,
  type TEXT CHECK (type IN ('value','doc','capability')) NOT NULL,
  subject TEXT,
  predicate TEXT,
  value_numeric REAL,
  value_text TEXT,
  value_bool INTEGER,
  unit TEXT,
  target_value REAL,
  slug TEXT,
  title TEXT,
  body_uri TEXT,
  doc_kind TEXT,
  status TEXT CHECK (
    status IN ('candidate','current','superseded','stale','archived')
  ) DEFAULT 'candidate',
  superseded_by TEXT REFERENCES knowledge(id),
  invalidation_reason TEXT,
  gate TEXT CHECK (gate IN ('auto','human')) NOT NULL,
  prescriptive INTEGER DEFAULT 0,
  inject INTEGER DEFAULT 0,
  risk TEXT CHECK (risk IN ('low','medium','high','critical')) DEFAULT 'low',
  confidence REAL,
  content_hash TEXT,
  loop_tags TEXT,
  project TEXT,
  privacy_scope TEXT CHECK (
    privacy_scope IN ('private','workspace','project','public')
  ) DEFAULT 'workspace',
  approved_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, origin TEXT, quarantine_reason TEXT, quality_label TEXT, quality_confidence REAL, quality_updated_at TEXT, promote_score REAL, embedding BLOB, embedded_at TEXT);
CREATE TABLE knowledge_evidence (
  knowledge_id TEXT NOT NULL REFERENCES knowledge(id),
  evidence_id TEXT NOT NULL REFERENCES evidence(id),
  relation TEXT CHECK (
    relation IN ('supports','contradicts','derived_from','supersedes')
  ),
  created_at TEXT NOT NULL,
  PRIMARY KEY (knowledge_id, evidence_id, relation)
);
CREATE TABLE loop_liveness (
  loop_id TEXT NOT NULL,
  run_id TEXT,
  last_heartbeat_at TEXT,
  last_ledger_write_at TEXT,
  expected_interval_seconds INTEGER,
  deadman_due_at TEXT,
  PRIMARY KEY (loop_id, run_id)
);
CREATE TABLE projection_cursor (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  last_event_rowid INTEGER,
  updated_at TEXT
);
CREATE TABLE retrieval_uses (
  id TEXT PRIMARY KEY,
  knowledge_id TEXT REFERENCES knowledge(id),
  served_to_runtime TEXT,
  task_ref TEXT,
  affected_decision INTEGER,
  corrected INTEGER,
  outcome TEXT CHECK (
    outcome IN (
      'improved','failed','neutral','unknown',
      'served','helpful','used','irrelevant','ignored','harmful'
    )
  ) DEFAULT 'unknown',
  note TEXT,
  query_text TEXT,
  served_ids_json TEXT,
  session_id TEXT,
  feedback_source TEXT,
  feedback_at TEXT,
  served_at TEXT NOT NULL,
  server_connection_id TEXT,
  client_session_hint TEXT,
  client_runtime_key TEXT,
  provenance_json TEXT,
  task_ref_norm TEXT
);
PRAGMA writable_schema=ON;
INSERT INTO sqlite_master(type,name,tbl_name,rootpage,sql)VALUES('table','search_index','search_index',0,'CREATE VIRTUAL TABLE search_index USING fts5(
  doc_id UNINDEXED,
  kind,
  title,
  body,
  path UNINDEXED
)');
CREATE TABLE 'search_index_config'(k PRIMARY KEY, v) WITHOUT ROWID;
INSERT INTO "search_index_config" VALUES('version',4);
CREATE TABLE 'search_index_content'(id INTEGER PRIMARY KEY, c0, c1, c2, c3, c4);
CREATE TABLE 'search_index_data'(id INTEGER PRIMARY KEY, block BLOB);
INSERT INTO "search_index_data" VALUES(1,X'');
INSERT INTO "search_index_data" VALUES(10,X'00000000000000');
CREATE TABLE 'search_index_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE 'search_index_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE signal_events (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  polarity TEXT NOT NULL,
  weight REAL NOT NULL,
  source TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  session_key TEXT,
  knowledge_id TEXT REFERENCES knowledge(id),
  evidence_id TEXT REFERENCES evidence(id),
  details TEXT,
  occurred_at TEXT,
  created_at TEXT NOT NULL
);
CREATE TABLE task_closeout_retrievals (
  closeout_id TEXT NOT NULL REFERENCES task_closeouts(id),
  retrieval_use_id TEXT NOT NULL REFERENCES retrieval_uses(id),
  PRIMARY KEY (closeout_id, retrieval_use_id)
);
CREATE TABLE task_closeouts (
  id TEXT PRIMARY KEY,
  schema_version TEXT NOT NULL,
  closed_at TEXT NOT NULL,
  task_ref TEXT NOT NULL,
  status TEXT NOT NULL,
  summary TEXT NOT NULL,
  decision_impact TEXT NOT NULL,
  decision_note TEXT,
  awaiting TEXT,
  runtime TEXT,
  session_id TEXT,
  context_json TEXT NOT NULL,
  artifact_refs_json TEXT NOT NULL,
  verifier_refs_json TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  receipt_json TEXT NOT NULL,
  content_hash TEXT NOT NULL UNIQUE,
  server_connection_id TEXT,
  client_session_hint TEXT,
  client_runtime_key TEXT,
  parent_closeout_id TEXT,
  task_ref_norm TEXT
);
CREATE INDEX idx_retrieval_uses_knowledge_outcome_served
  ON retrieval_uses(knowledge_id, outcome, served_at);
CREATE INDEX idx_brain_events_kind_ts ON brain_events(kind, ts);
CREATE INDEX idx_brain_events_correction_target
  ON brain_events(json_extract(body_json, '$.target_id'))
  WHERE kind = 'correction_recorded';
CREATE INDEX idx_current_beliefs_scope
  ON current_beliefs(scope_type, scope_id, status);
CREATE INDEX idx_knowledge_updated_id ON knowledge(updated_at, id);
CREATE INDEX idx_sig_knowledge ON signal_events(knowledge_id, created_at);
CREATE INDEX idx_sig_kind ON signal_events(kind, created_at);
CREATE INDEX idx_sig_session ON signal_events(session_key);
CREATE INDEX idx_judge_ts ON judge_runs(ts);
CREATE INDEX idx_dsx_dataset_label ON dataset_examples(dataset, quality_label);
CREATE INDEX idx_dsx_dedup ON dataset_examples(dataset, dedup_key);
CREATE INDEX idx_dsx_occurred ON dataset_examples(dataset, occurred_at);
CREATE INDEX idx_dataset_grade_runs_ts ON dataset_grade_runs(ts);
CREATE INDEX idx_embed_runs_ts ON embed_runs(ts);
CREATE INDEX idx_context_source_handles_retrieval
  ON context_source_handles(retrieval_use_id);
CREATE INDEX idx_context_source_handle_issues_retrieval
  ON context_source_handle_issues(retrieval_use_id);
CREATE TRIGGER context_source_handle_issues_no_update
BEFORE UPDATE ON context_source_handle_issues BEGIN
  SELECT RAISE(ABORT, 'context_source_handle_issues is append-only');
END;
CREATE TRIGGER context_source_handle_issues_no_delete
BEFORE DELETE ON context_source_handle_issues BEGIN
  SELECT RAISE(ABORT, 'context_source_handle_issues is append-only');
END;
CREATE INDEX idx_task_closeouts_chain
  ON task_closeouts(task_ref_norm, closed_at);
CREATE INDEX idx_task_closeout_retrievals_retrieval
  ON task_closeout_retrievals(retrieval_use_id);
CREATE TRIGGER task_closeouts_no_update
BEFORE UPDATE ON task_closeouts BEGIN
  SELECT RAISE(ABORT, 'task_closeouts is append-only');
END;
CREATE TRIGGER task_closeouts_no_delete
BEFORE DELETE ON task_closeouts BEGIN
  SELECT RAISE(ABORT, 'task_closeouts is append-only');
END;
CREATE TRIGGER task_closeout_retrievals_no_update
BEFORE UPDATE ON task_closeout_retrievals BEGIN
  SELECT RAISE(ABORT, 'task_closeout_retrievals is append-only');
END;
CREATE TRIGGER task_closeout_retrievals_no_delete
BEFORE DELETE ON task_closeout_retrievals BEGIN
  SELECT RAISE(ABORT, 'task_closeout_retrievals is append-only');
END;
CREATE INDEX idx_dsx_grade ON dataset_examples(dataset, grade_score);
CREATE INDEX idx_dsx_train_class ON dataset_examples(dataset, train_class, grade_score);
CREATE INDEX idx_dsx_train_selected ON dataset_examples(dataset, train_selected, train_class, grade_score);
CREATE INDEX idx_retrieval_feedback_pending ON retrieval_uses(outcome, served_at);
CREATE VIEW memory AS
  SELECT * FROM knowledge
  WHERE status = 'current' AND inject = 1 AND quarantine_reason IS NULL;
PRAGMA writable_schema=OFF;
COMMIT;
