from __future__ import annotations

import re
from pathlib import Path

from ocbrain.db import REVIEWED_OUTPUT_STATUSES, list_candidates, log_retrieval_use

BEGIN = "<!-- BEGIN OCBRAIN MANAGED BLOCK -->"
END = "<!-- END OCBRAIN MANAGED BLOCK -->"


def build_excerpt(
    conn,
    runtime: str,
    scope: str | None = None,
    limit: int = 12,
    status: str | None = None,
    include_draft: bool = False,
) -> str:
    statuses = None if status or include_draft else REVIEWED_OUTPUT_STATUSES
    rows = list_candidates(
        conn,
        status=status,
        statuses=statuses,
        scope=scope,
        limit=limit * 5,
    )
    lines = [
        BEGIN,
        f"<!-- runtime={runtime}; generated by ocbrain; edit source candidates, not this block -->",
        "",
        "## ocbrain Shared Context",
        "",
    ]
    count = 0
    for row in rows:
        if row["target"] == "ignore":
            continue
        if row["scope"] == "private" and scope != "private":
            continue
        if row["risk"] == "high" and row["status"] not in {"approved", "applied"}:
            continue
        title = row["title"][:180]
        lines.append(
            f"- [{row['target']}/{row['risk']}/{row['status']}] {title} [{row['id']}]"
        )
        count += 1
        if count >= limit:
            break
    if count == 0:
        lines.append("- No current ocbrain candidates for this scope.")
    lines += ["", END, ""]
    return "\n".join(lines)


def write_excerpt(
    conn,
    output_path: Path,
    runtime: str,
    scope: str | None,
    limit: int,
    status: str | None = None,
    include_draft: bool = False,
) -> Path:
    block = build_excerpt(conn, runtime, scope, limit, status, include_draft)
    wrote_path = output_path
    if output_path.exists():
        existing = output_path.read_text(encoding="utf-8")
        start = existing.find(BEGIN)
        end = existing.find(END)
        if start != -1 and end != -1 and end >= start:
            end += len(END)
            new_text = existing[:start] + block.rstrip() + existing[end:]
            output_path.write_text(new_text.rstrip() + "\n", encoding="utf-8")
            log_excerpt_retrievals(conn, block, runtime, scope, status, limit, wrote_path)
            conn.commit()
            return output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    prefix = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
    output_path.write_text((prefix.rstrip() + "\n\n" + block).lstrip(), encoding="utf-8")
    log_excerpt_retrievals(conn, block, runtime, scope, status, limit, wrote_path)
    conn.commit()
    return output_path


def log_excerpt_retrievals(
    conn,
    block: str,
    runtime: str,
    scope: str | None,
    status: str | None,
    limit: int,
    output_path: Path,
) -> None:
    query = f"scope={scope or '*'};status={status or 'reviewed'};limit={limit}"
    for candidate_id in re.findall(r"\[(cand_[a-z0-9]+)\]$", block, flags=re.MULTILINE):
        log_retrieval_use(
            conn,
            candidate_id,
            runtime=f"excerpt:{runtime}",
            query=query,
            outcome="included",
            note=str(output_path),
        )
