from __future__ import annotations

from pathlib import Path

from ocbrain.db import list_candidates

BEGIN = "<!-- BEGIN OCBRAIN MANAGED BLOCK -->"
END = "<!-- END OCBRAIN MANAGED BLOCK -->"


def build_excerpt(conn, runtime: str, scope: str | None = None, limit: int = 12) -> str:
    rows = list_candidates(conn, status=None, limit=limit * 3)
    lines = [
        BEGIN,
        f"<!-- runtime={runtime}; generated by ocbrain; edit source candidates, not this block -->",
        "",
        "## ocbrain Shared Context",
        "",
    ]
    count = 0
    for row in rows:
        if row["target"] == "ignore":
            continue
        if scope and row["scope"] != scope:
            continue
        lines.append(f"- {row['title']} [{row['id']}]")
        count += 1
        if count >= limit:
            break
    if count == 0:
        lines.append("- No current ocbrain candidates for this scope.")
    lines += ["", END, ""]
    return "\n".join(lines)


def write_excerpt(conn, output_path: Path, runtime: str, scope: str | None, limit: int) -> Path:
    block = build_excerpt(conn, runtime, scope, limit)
    if output_path.exists():
        existing = output_path.read_text(encoding="utf-8")
        start = existing.find(BEGIN)
        end = existing.find(END)
        if start != -1 and end != -1 and end >= start:
            end += len(END)
            new_text = existing[:start] + block.rstrip() + existing[end:]
            output_path.write_text(new_text.rstrip() + "\n", encoding="utf-8")
            return output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    prefix = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
    output_path.write_text((prefix.rstrip() + "\n\n" + block).lstrip(), encoding="utf-8")
    return output_path
